from __future__ import annotations

import json
from pathlib import Path

from ..model import ResolvedVehicle


def resolved_parameters(vehicle: ResolvedVehicle) -> tuple[dict[str, float], dict[str, str]]:
    parameters = dict(vehicle.components.controller.parameters)
    origins = dict(vehicle.components.controller.parameter_origins)
    generated = {
        "SIMULATION_DELTA_TIME": 0.001,
        "MASS": vehicle.total_mass_kg,
        "ANGLE_CONTROL_ENABLE": 1.0 if vehicle.recipe.controller_mode == "angle" else 0.0,
        "ANGLE_RATE_CONTROL_ENABLE": 1.0 if vehicle.recipe.controller_mode == "rate" else 0.0,
        "ALT_SPD_CONTROL_ENABLE": 0.0,
    }
    for key, value in generated.items():
        parameters[key] = value
        origins[key] = "generated_initial"
    return parameters, origins


def generate_control_parameters(vehicle: ResolvedVehicle, json_output: Path, runtime_output: Path) -> None:
    parameters, origins = resolved_parameters(vehicle)
    structured = {
        "schema_version": 1,
        "backend": vehicle.components.controller.backend,
        "mode": vehicle.recipe.controller_mode,
        "runtime_format": "hakoniwa-controller-param-text-v1",
        "runtime_file": runtime_output.name,
        "parameters": {
            key: {"value": parameters[key], "origin": origins[key]}
            for key in sorted(parameters)
        },
        "notes": [
            "control-param.json records value provenance; Hakoniwa Drone PRO currently consumes control-param.txt.",
            "These are initial values, not values validated for a real aircraft.",
        ],
    }
    json_output.write_text(json.dumps(structured, indent=2) + "\n", encoding="utf-8")
    lines = ["# Generated by hakoniwa-fpv-drone. Initial values require tuning."]
    for key in sorted(parameters):
        lines.append(f"{key:<44} {parameters[key]:.12g}")
    runtime_output.write_text("\n".join(lines) + "\n", encoding="utf-8")
